RECTANGLE = 'rectangle'
LINE = 'line'
TEXT = 'text'
TEXT_BOX = 'text_box'

SHAPES = 'SHAPES'
EVENT = 'event'
X = 'x'
Y = 'y'
SHAPE_UNDER_MOUSE = 'SHAPE_UNDER_MOUSE'
CLICKED_POSITION = 'CLICKED_POSITION'
SHAPES_SELECTED = 'SHAPES_SELECTED'

# commands
DRAW_RECTANGLE = 'DRAW_RECTANGLE'
SET_RECTANGLE_WIDTH = 'SET_RECTANGLE_WIDTH'
SET_RECTANGLE_BORDER_COLOR = 'SET_BORDER_COLOR'
SET_RECTANGLE_FILL_COLOR = 'SET_RECTANGLE_FILL_COLOR'
SET_RECTANGLE_BORDER_WIDTH = 'SET_RECTANGLE_BORDER_WIDTH'

# mouse events
Mouse_In = 'Mouse In'
Mouse_Out = 'Mouse Out'
Mouse_Motion_At = 'Mouse Motion At'

Left_Click = 'Left Click'
Left_Click_Drag = 'Left Click Drag'
Left_Click_Release = 'Left Click Release'

Right_Click = 'Right Click'
Right_Click_Drag = 'Right Click Drag'
Right_Click_Release = 'Right Click Release'

Middle_Click = 'Middle Click'
Middle_Click_Drag = 'Middle Click Drag'
Middle_Click_Release = 'Middle Click Release'

SHIFT_Left_Click = 'SHIFT Left Click'
SHIFT_Left_Click_Drag = 'SHIFT Left Click Drag'
SHIFT_Left_Click_Release = 'SHIFT Left Click Release'
SHIFT_Right_Click = 'SHIFT Right Click'
SHIFT_Right_Click_Drag = 'SHIFT Right Click Drag'
SHIFT_Right_Click_Release = 'SHIFT Right Click Release'
SHIFT_Middle_Click = 'SHIFT Middle Click'
SHIFT_Middle_Click_Drag = 'SHIFT Middle Click Drag'
SHIFT_Middle_Click_Release = 'SHIFT Middle Click Release'

CONTROL_Left_Click = 'CONTROL Left Click'
CONTROL_Left_Click_Drag = 'CONTROL Left Click Drag'
CONTROL_Left_Click_Release = 'CONTROL Left Click Release'
CONTROL_Right_Click = 'CONTROL Right Click'
CONTROL_Right_Click_Drag = 'CONTROL Right Click Drag'
CONTROL_Right_Click_Release = 'CONTROL Right Click Release'
CONTROL_Middle_Click = 'CONTROL Middle Click'
CONTROL_Middle_Click_Drag = 'CONTROL Middle Click Drag'
CONTROL_Middle_Click_Release = 'CONTROL Middle Click Release'

COMMAND_Left_Click = 'COMMAND Left Click'
COMMAND_Left_Click_Drag = 'COMMAND Left Click Drag'
COMMAND_Left_Click_Release = 'COMMAND Left Click Release'
COMMAND_Right_Click = 'COMMAND Right Click'
COMMAND_Right_Click_Drag = 'COMMAND Right Click Drag'
COMMAND_Right_Click_Release = 'COMMAND Right Click Release'
COMMAND_Middle_Click = 'COMMAND Middle Click'
COMMAND_Middle_Click_Drag = 'COMMAND Middle Click Drag'
COMMAND_Middle_Click_Release = 'COMMAND Middle Click Release'

Alt_Left_Click = 'Alt Left Click'
Alt_Left_Click_Drag = 'Alt Left Click Drag'
Alt_Left_Click_Release = 'Alt Left Click Release'
Alt_Right_Click = 'Alt Right Click'
Alt_Right_Click_Drag = 'Alt Right Click Drag'
Alt_Right_Click_Release = 'Alt Right Click Release'
Alt_Middle_Click = 'Alt Middle Click'
Alt_Middle_Click_Drag = 'Alt Middle Click Drag'
Alt_Middle_Click_Release = 'Alt Middle Click Release'
