RECTANGLE = 'rectangle'
LINE = 'line'
TEXT = 'text'
TEXT_BOX = 'text_box'

# commands
DRAW_RECTANGLE = 'DRAW_RECTANGLE'
SET_RECTANGLE_WIDTH = 'SET_RECTANGLE_WIDTH'
SET_RECTANGLE_BORDER_COLOR = 'SET_BORDER_COLOR'
SET_RECTANGLE_FILL_COLOR = 'SET_RECTANGLE_FILL_COLOR'
SET_RECTANGLE_BORDER_WIDTH = 'SET_RECTANGLE_BORDER_WIDTH'
